--

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,30 +8,29 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    
     steps:
-    - name: Code checkout
-    - uses: actions/checkout@v3
+      - name: Code checkout
+        uses: actions/checkout@v3
     
-    - name: Node.js setup
-      uses: actions/setup-node@v3
-      with:
-        node-version: '23'
-        cache: 'npm'
+      - name: Node.js setup
+        uses: actions/setup-node@v3
+        with:
+          node-version: '23'
+          cache: 'npm'
         
-    - name: Install dependencies
-      run: npm ci
+      - name: Install dependencies
+        run: npm ci
       
-    - name: Build
-      run: |
-        npm run build
-      continue-on-error: false
+      - name: Build
+        run: |
+          npm run build
+        continue-on-error: false
       
-    - name: Build errors?
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Build failed!"
-          exit 1
-        else
-          echo "Success"
-        fi
+      - name: Build errors?
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Build failed!"
+            exit 1
+          else
+            echo "Success"
+          fi
